### ISSUE TITLE
Make closing the get info dialog delete evidence

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#3]
Currently if you close the window via the close button (or other methods other than the delete button) it does not cause the evidence to be delete. This should not be the case. Any action, other than submit, should result in the evidence being deleted.

**Comment by JoelAtDeluxe** [comment]
I don't know if this is a good idea, or at least we need to define this flow a bit better. There are two situations to consider: a user is able to submit, and a user is unable to submit (say, due to a network outage).

If they are able to submit, then having the close button delete works -- it just duplicates the effect of the delete button. Submit, obviously, still submits.

If they are unable to submit, then there's a bit of an issue. Presumably they want to keep this evidence around and retry later. If the close button and the delete button delete the content, and submit doesn't work... then the only option; is to keep the window open. What should be done in this case? Are we okay with just requiring that the user keep the always-on-top window open, or to duplicate their work later, or should we allow saving with the intent to submit later?

Some possible options if we want to allow saving:
* Only show the "save & close" button after the user tries to submit (And fails)
* Submit implicitly saves, and if there's an issue submitting, a prompt indicates this, and then closes anyway (allowing the user to go to the management area to re-submit)
* Some background process tries to submit this periodically, if the initial submit fails
* Close works conditionally: If not submitted, deletes. If a submit has occurred, it acts as a save.

Thoughts?

**Comment by JoelAtDeluxe** [comment]
Closing per off-line conversation
