### ISSUE TITLE
Connection Test Returns Wrong Status

### ISSUE THREAD

**Issue by jkennedyvz** [ashirt-ops/ashirt#50]
**Golang version** (`go version`):
go version go1.14.1 darwin/amd64
**OS version** (`uname -a` if on a Unix-like system):
19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020
**Description of the problem including expected versus actual behavior**:

Ashirt client gives "Connected" when accessing the URL for the UI, even if incorrect keys are submitted. Ashirt client should ensure it is connected to the API before returning "Connected"

**Steps to reproduce**:

<img width="754" alt="Screen Shot 2020-09-14 at 11 44 56 AM" src="https://user-images.githubusercontent.com/65985482/93125558-2ed24380-f680-11ea-9fc1-7386de11fa90.png">

<img width="752" alt="Screen Shot 2020-09-14 at 11 44 47 AM" src="https://user-images.githubusercontent.com/65985482/93125565-3265ca80-f680-11ea-9146-10006d43524e.png">

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by JoelAtDeluxe** [comment]
Ah, yeah, this is a weird corner case. The method we use to construct the json request is the same for both normal requests and the test connection, where we can specify what the value should be. It determines whether to use the saved key and secret  based on what's passed in: if the strings are empty, then it uses the saved values. Since you emptied out the key and secret fields, it looks like just a normal request, unfortunately. 

Rather than attempt a request that clearly will not work, instead a check will be added to ensure that these values are set to _something_ before we run the connection check. If one of those 3 values (Access Key, Secret Key, or Host Path), then an error message will be displayed instead.
